version: 2

models:
  - name: fact_commits
    description: "Final table of commits from the repo"
    columns:
      - name: commit_hash
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

      - name: author_name
        tests:
          - not_null