name: 'my_pipeline'
version: '1.0.0'
config-version: 2

# This matches the "my_pipeline" inside your profiles.yml
profile: 'my_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_pipeline:
    # Configures all models in this project
    +materialized: view